kubectl apply -f replicaset-viewer-role.yamlreplicaset-viewer-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: replicaset-viewer
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replicaset-viewer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: replicaset-viewer
subjects:
  - kind: ServiceAccount
    name: chlwndks3-sa
    namespace: chlwndks3-namespace