apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: default  # Secret이 있는 네임스페이스
subjects:
  - kind: ServiceAccount
    name: chlwndks3-sa
    namespace: default  # 서비스 어카운트가 속한 네임스페이스
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
