apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: chlwndks3-namespace
subjects:
  - kind: ServiceAccount
    name: chlwndks3-sa
    namespace: chlwndks3-namespace
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
